#!/usr/bin/env bash

host="$1"
function readfile() {
    local data=""
    while read -r line; do
        data="$data$line"
    done < "$1"
    echo "${data}"
}

curl -X PUT "$host:9200/_template/my_template" \
     -H "Content-Type: application/json" \
     -d "$(readfile /path/to/tempalte)"
curl -X POST "$host:5601/api/saved_objects/_bulk_create?overwrite=true" \
     -H "kbn-xsrf: true" \
     -H "Content-Type: application/json" \
     -d "$(readfile ${objects_path})"
curl -X POST "$host:5601/api/kibana/settings/visualization:regionmap:showWarnings" \
     -H "kbn-xsrf: true" \
     -H "Content-Type: application/json" \
     -d '{"value": false}'
