--- # contents of the /etc/sensor/conf.d/example.conf

# capture interface and mode
# interface option is mandatory
sensor:
  interface: "eno1"
  # one of [ in , out , promisc ] default direction = > promisc
  direction: "promisc"

# Filebeat connection specification
# default host = > localhost :12000
beats:
  host: "elk.bp.local"
  port: 12000