---

filter:
  src: true
  dst: true

sensor:
  interface: false
  direction: true

database:
  beats:
    host: true
    port: true
  elastic:
    host: true
    port: true
  archive:
    path: true
    limit: true