--- # contents of the /etc/sensor/conf.d/example.conf

# capture interface and direction mode
# default interface => not specified
# default direction => promisc
# archive output path and archivation condition
sensor:
#  interface: eth1
  direction: in

# filters as allowed traffic
# default => not specified
filter:
  src: 10.0.100.56
  dst: 8.8.8.8

# Filebeat connection specification
# default host => localhost:12000
# Elasticseach connection specification
# default => localhost:9200
# archive path default => /etc/sensor/
# archive limit default => 10000 [MB]
database:
  beats:
    host: 192.148.56.4
    port: 12000
  elastic:
    host: 192.148.56.4
    port: 9200
  archive:
    path: "/home/user/sensor_archive/"
    limit: 50000
