#ifndef TRAFFIC_COLLECTOR_CONFIG_FILES_H
#define TRAFFIC_COLLECTOR_CONFIG_FILES_H


#define SPECS_CONFIG_PATH "resources/config_specs.yml"
#define CONFIG_FULL_PATH "resources/traffcol.yml"

#define DEFAULT_BEATS_HOST "127.0.0.1"
#define DEFAULT_BEATS_PORT 12000


#endif //TRAFFIC_COLLECTOR_CONFIG_FILES_H